-- --------------------------------------------------------
-- Sunucu:                       127.0.0.1
-- Sunucu sürümü:                10.4.14-MariaDB - mariadb.org binary distribution
-- Sunucu İşletim Sistemi:       Win64
-- HeidiSQL Sürüm:               11.1.0.6116
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- recipes için veritabanı yapısı dökülüyor
DROP DATABASE IF EXISTS `recipes`;
CREATE DATABASE IF NOT EXISTS `recipes` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_turkish_ci */;
USE `recipes`;

-- tablo yapısı dökülüyor recipes.banners
DROP TABLE IF EXISTS `banners`;
CREATE TABLE IF NOT EXISTS `banners` (
  `banner_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(80) COLLATE utf8_turkish_ci DEFAULT NULL,
  `description` varchar(150) COLLATE utf8_turkish_ci DEFAULT NULL,
  `image` varchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `link` varchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `seq` int(11) DEFAULT NULL,
  `visible` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`banner_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.banners: ~4 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `banners` DISABLE KEYS */;
INSERT INTO `banners` (`banner_id`, `title`, `description`, `image`, `link`, `seq`, `visible`) VALUES
	(1, 'Nefis Mercimek Çorbası', 'Yöresel tatlar arasında müstesna bir yeri olan çorbamızı birde bu tarifle deneyin', 'slider1.jpg', '/tarifler/7', 1, 1),
	(2, 'Alinazik', 'Etin yoğrut ile en güzel şekilde harmanlandığı bir tarif', 'slider2.jpg', '/tarifler/13', 2, 1),
	(3, 'Tava Böreği', 'SAbah kahvaltılarının ve ikindi çaylarının vazgeçilmez tadı', 'slider3.jpg', '/tarifler/18', 3, 1),
	(4, 'Yeşil Detoks Çorbası', 'Diyette olanlar için mükemmel bir çorba önerimiz var', 'slider4.jpg', '/tarifler/7', 4, 1);
/*!40000 ALTER TABLE `banners` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.categories
DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `category_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) COLLATE utf8_turkish_ci NOT NULL,
  `seq` int(11) DEFAULT NULL,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.categories: ~5 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`category_id`, `title`, `seq`) VALUES
	(1, 'Börek', 1),
	(2, 'Çorba', 2),
	(3, 'Et', 3),
	(4, 'Hamur İşi', 4),
	(5, 'Diyet', 5);
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.comments
DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
  `comment_id` int(11) NOT NULL AUTO_INCREMENT,
  `comment` mediumtext COLLATE utf8_turkish_ci DEFAULT NULL,
  `create_date` date DEFAULT NULL,
  `rating` double DEFAULT NULL,
  `name` varchar(70) COLLATE utf8_turkish_ci DEFAULT NULL,
  `email` varchar(80) COLLATE utf8_turkish_ci DEFAULT NULL,
  `visible` tinyint(4) DEFAULT NULL,
  `recipe` int(11) DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  KEY `FK_comments_recipes` (`recipe`),
  CONSTRAINT `FK_comments_recipes` FOREIGN KEY (`recipe`) REFERENCES `recipes` (`recipe_id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.comments: ~14 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `comments` DISABLE KEYS */;
INSERT INTO `comments` (`comment_id`, `comment`, `create_date`, `rating`, `name`, `email`, `visible`, `recipe`) VALUES
	(1, 'bayıldım çocuklarım da buna bayilicak Teşekkürler özge hanım', '2021-01-20', 5, 'Emine Fırat', 'eminef@gmail.com', 1, 1),
	(2, 'cok guzel gorunuyolar fakat hic aciklayici bir tarif degil un nekadar olcak kivami nasil olcak. biraz daha detayli anlatirsaniz sewinirim.', '2021-01-20', 3, 'Kübra Konuk', 'kubrak@gmail.com', 1, 1),
	(3, 'Bu tarifte kek hamurunda yağ yok mu? Görsel olarak çok güzel gözüküyor ellerinize sağlık', '2021-01-20', 4, 'SEvcan Seher', 'sevcans@gmail.com', 1, 2),
	(4, 'keki kağıt kapsülde pişirdim ona çok yapıştı,yarısınıda küçük borcamda pişirdim.pişirmek pandispanya gibi dikkat gerektiriyor,tadı fena olmadı,jolenin şekerini ayarladım güzel oldu;) elinize sağlık', '2021-01-20', 4, 'Pelin Hisar', 'pelinh@gmail.com', 1, 3),
	(5, 'Ben yaptım kek katı oldu çok güzel karardı fakat şeker de verdiğiniz ölçü az olduğu', '2021-01-20', 4, 'Sinan Kara', 'sinan@gmail.com', 1, 3),
	(6, 'Ben göz kararı un koyuyorum fakat sizler 5 fincan kadar un koyabilirsiniz yeterli olacaktır :) afiyetler olsun kusura bakmayın yeni girebildim', '2021-01-20', 4, 'Berna Sağlar', 'berna@gmail.com', 1, 4),
	(7, 'Normal kek kıvamında bu tarif. O kıvamı göz önünde tutarak ununuzu koyabilirsiniz', '2021-01-20', 4, 'Asu Kaya', 'asu@gmail.com', 1, 4),
	(8, 'Bayan nasıl yaptı bilmiyorum ama sizin için söylim savaren kalıpları var. Ortası delikli çıkartıyor kekleri. Marmelatyerini . Siz de o kalıplardan kullanabilirsiniz', '2021-01-20', 4, 'Aslıhan Gök', 'aslihan@gmail.com', 1, 5),
	(9, 'çok güzel görünüyor ellerinize saglik.ama lütfen biraz daha aciklarmiainiz tam nasil yaptinizi.', '2021-01-20', 3, 'Sevinç Çelenk', 'sevinc@gmail.com', 1, 5),
	(10, 'Su eklenildigi taktirde cok güzel oluyor, cok begendim, cok tesekkürler ', '2021-01-20', 5, 'Ceyda Civelek', 'ceyda@gmail.com', 1, 2),
	(11, 'Yaptım efsane oldu. Çok teşekkür ederim', '2021-01-20', 5, 'Hayal Kandemir', 'hayal@gmail.com', 1, 2),
	(12, 'tahini 1/3 demissiniz yarim su bardagimi oluyor acaba', '2021-01-20', 4, 'Leyla Şanlı', 'leyla@gmail.com', 1, 2),
	(13, 'birebir uydum olmadı. başaranlari tebrik ederim', '2021-01-20', 2, 'Feyza Seyyar', 'feyza@gmail.com', 1, 2),
	(14, 'kıvamı katı oldu. smootie cihazında çektim nohutu ve baya bi su eklemek durumunda kaldım. onun dışında oranlar güzel.', '2021-01-20', 3, 'Talat Tar', 'talat@gmail.com', 1, 2);
/*!40000 ALTER TABLE `comments` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.directions
DROP TABLE IF EXISTS `directions`;
CREATE TABLE IF NOT EXISTS `directions` (
  `direction_id` int(11) NOT NULL AUTO_INCREMENT,
  `direction` mediumtext COLLATE utf8_turkish_ci DEFAULT NULL,
  `recipe` int(11) DEFAULT NULL,
  PRIMARY KEY (`direction_id`),
  KEY `FK_directions_recipes` (`recipe`),
  CONSTRAINT `FK_directions_recipes` FOREIGN KEY (`recipe`) REFERENCES `recipes` (`recipe_id`)
) ENGINE=InnoDB AUTO_INCREMENT=162 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.directions: ~161 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `directions` DISABLE KEYS */;
INSERT INTO `directions` (`direction_id`, `direction`, `recipe`) VALUES
	(1, 'Kıymalı iç harcı için kuru soğanı küçük parçalar halinde doğrayın. Bol suda yıkayıp fazla suyunu süzdürdüğünüz ayıklanmış maydanoz yapraklarını incecik kıyın. Ceviz içini keskin bir bıçak yardımıyla kıyın.', 1),
	(2, 'Kapaklı küçük bir kaseye aldığınız köftelik ince bulgurun üzerini örtecek kadar sıcak su ekleyin. Kapağını kapatıp şişmesi için kısa bir süre bekletin.', 1),
	(3, 'Tereyağı ve sıvı yağı bir tavaya alıp kızdırın.', 1),
	(4, 'Soğanları ekleyip, soğanlar diriliğini kaybedene kadar kavurma işlemini sürdürün.', 1),
	(5, 'Soğanların üzerine kıymayı, tuz ve karabiberi ekleyin ve kavurma işlemine devam edin.', 1),
	(6, 'Kavrulan kıymanın üzerine ceviz, şişmiş ince bulgur ve doğranmış maydanozu ekleyip karıştırın ve ocağın altını kapatın.', 1),
	(7, 'Yufkaları dörde bölün ve her birini fırça ile yağlayın.', 1),
	(8, 'Yufkanın geniş kısmına kıymalı harçtan ekleyin ve önce kenarlardan katlayarak rulo haline getirip kapatın.', 1),
	(9, 'Yumurtaları geniş bir kapta çırpın. Elenmiş galeta ununu düz bir tabağa alın. Hazırladığınız avcı böreklerini öncelikle çırpılmış yumurtaya ardından galeta ununa bulayın.', 1),
	(10, 'Kızgın yağda kızartın ve sıcak olarak servis edin, sevdiklerinizle afiyetle yiyin.', 1),
	(11, 'Bir kasenin içerisinde süt, su, sıvı yağ ve yumurtayı çırpıp güzelce karıştırın.', 2),
	(12, 'Beyaz peynir, kaşar peyniri ve maydanozu karıştırın.', 2),
	(13, 'Yuvarlak fırın tepsisini yağlayın ve en alt katmanına ilk yufkanızı kenarları dışarıdan sarkacak şekilde yerleştirin. Üzerine 1 kepçe sütlü karışımı ekleyip güzelce yayın.', 2),
	(14, 'Kalan 5 yufkanın 4`ünü iri parçalara bölün.', 2),
	(15, 'Hazırladığınız sütlü karışımın içerisine yufkaları batırıp tamamen harca bulanmasını sağlayın.', 2),
	(16, 'Yufkaların ikisini ilk kat yufkanın üzerine gelişi güzel serin ve iç harcın yarısını bu kata koyun.', 2),
	(17, 'Kalan yufkaları harcın üzerini örtecek şekilde yerleştirin. En son ilk yufkanın kenarlarını tepsinin içerisine doğru kapatın ve sütlü karışımdan üzerine sürün.', 2),
	(18, 'Son yufkayı da üzerini güzelce kapatacak şekilde tepsiye serin ve kalan sütlü karışımdan üzerine ilave ettikten sonra çırpılmış yumurta ve susam serpiştirin.', 2),
	(19, 'Böreği dilimleyerek 195 derece fansız programda ısıtılmış fırında üzeri kızarıp yufkalar kat kat ayrılana dek, kontrollü olarak pişirin.', 2),
	(20, 'Oda sıcaklığında ılımaya bırakın ve servis edin. Afiyet olsun!', 2),
	(21, 'Yufkayı tezgaha serin. Üzerine eritilmiş tereyağını gezdirin ve diğer yufkayı da üzerine serip aynı şekilde eritilmiş tereyağını üzerine yayın.', 3),
	(22, 'İki kat yağlanmış yufkaları 12 eşit üçgen parçaya bölün.', 3),
	(23, 'Her bir üçgenin geniş kısmına lor peynirli, maydanozlu harçtan ekleyin ve kenarlardan katlayıp, rulo börek şeklinde katlayın.', 3),
	(24, 'Soda dolu kabın içerisine tüm börekleri ekleyin ve 10 dakika dinlendirin.', 3),
	(25, 'Dinlendirdiğiniz börekleri soda banyosundan çıkarın ve hafif sıkıp pişirme kağıdı serili fırın tepsisine yerleştirin.', 3),
	(26, 'Üzerlerine yumurta sarısı sürüp, susam ve çörek otu serpiştirin.', 3),
	(27, '180 derece fırında 30 dakika pişirin. İlk sıcaklığı geçtikten sonra afiyetle yiyin!', 3),
	(28, 'Bir karıştırma kabının içinde 300 gram kıyma, 1 adet soğan rendesi, 1 tatlı kaşığı karabiber, 1 tatlı kaşığı tuz ve yarım çay bardağı suyu karıştırın.', 4),
	(29, 'Harcınızın sulu olmasına özen gösterin.', 4),
	(30, 'Bir kabın içerisinde 1 su bardağı ılık su, 3 su bardağı un, 1 tatlı kaşığı tuz ve 2 tatlı kaşığı üzüm ya da elma sirkesini karıştırın.', 4),
	(31, 'Orta yumuşaklıkta bir hamur elde edene kadar yoğurun.', 4),
	(32, 'Hamurunuzu un serptiğiniz tezgaha alıp bezelere ayırın.', 4),
	(33, 'Bir merdane yardımıyla orta büyüklükte bir tabak boyutunda açın. (Çiğ böreğinizin çıtır çıtır olmasını istiyorsanız hamurunuzu ince, daha dolgun olmasını istiyorsanız orta kalınlıkta açın.)', 4),
	(34, 'Kıymalı harcınızı açtığınız hamura yerleştirip katlayın.', 4),
	(35, 'Kenarlarının iyice yapışmasını sağlamak için bir kapak ya da pizza kesiciyle düzgünce kesin.', 4),
	(36, 'Hepsini bu şekilde hazırlayın.', 4),
	(37, 'Bu sayede, börekleriniz kızarırken kenarları açılmayacaktır. Derin bir tavaya yağı alın ve güzelce kızdırın.', 4),
	(38, 'Kızmış yağa börekleri atarak kızartın ve kızaran böreklerinizi fazla yağı emmesi için bir kağıt havlu üzerine alın. Afiyet olsun.', 4),
	(39, 'Derin bir kasede yumurta, sıvı yağ, süt, kabartma tozu, tuz, karabiber, kimyon, pul biber ve kırmızı toz biberi ekleyip çırpın.', 5),
	(40, 'Üzerine un ve mısır ununu ekleyip karıştırın.', 5),
	(41, 'Son olarak kibrit doğranmış patates, soğan, kaşar peyniri, beyaz peynir ve maydanozu ekleyip güzelce karıştırın.', 5),
	(42, 'Yağlanmış fırın kabına hazırladığınız harcı ekleyin. Önceden ısıtılmış 180 derece fırında 40 dakika pişirin.', 5),
	(43, 'Frından çıkan böreğin ilk sıcaklığı geçtikten sonra dilimleyin.', 5),
	(44, 'Üzerine arzuya göre çırpılmış yoğurt ve maydanoz serpiştirerek servis edin. Afiyet olsun!', 5),
	(45, 'Bir tavada zeytinyağı ile soğanları kavurun.', 6),
	(46, 'Ispanakları güzelce yıkayıp iri parçalar halinde doğrayın. Daha sonra üzerine ayıklayıp yıkadığınız ıspanakları, karabiberi ve tuzu ekleyip kavurun.', 6),
	(47, 'Ispanaklar suyunu salınca ocağın altını kapatın ve ıspanakları bir kenarda soğumaya bırakın.', 6),
	(48, 'Bir kabın içerisinde bir bardak yoğurt, 2 adet yumurta,  yarım çay bardağı su ve yarım çay bardağı sıvı yağı güzelce çırpın.', 6),
	(49, 'Fırın tepsisini yağladıktan ya da bir pişirme kağıdı serdikten sonra bir adet yufkayı tepsinin kenarlarından taşacak şekilde içine serin.', 6),
	(50, 'Yoğurtlu karışımı bir fırça yardımıyla yufkanın üzerine sürün.', 6),
	(51, 'İkinci yufkayı buruşturarak birinci yufkanın üzerine yerleştirin.', 6),
	(52, 'Üzerine yoğurtlu karışımdan sürdükten sonra üzerine ıspanaklı harcın bir kısmını ekleyin.', 6),
	(53, 'Üzerine üçüncü yufkayı buruşturarak yerleştirin. Yoğurtlu karışımı sürüp dördüncü yufkayı yerleştirin.', 6),
	(54, 'Dördüncü yufkanın üzerine yoğurtlu karışımdan sürüp kalan ıspanak harcını ekleyin.', 6),
	(55, 'Beşinci yufkayı serip üzerine yoğurtlu karışımdan sürdükten sonra en altta kalan ve tepsi dışına taşan yufkayı da tepsi üzerine toplayın. Üzerine kalan yoğurtlu karışımı sürün.', 6),
	(56, 'Böreği dilimlere ayırıp üzerilerine yumurta sarısı sürün ve arzunuza göre üzerini çörek otuyla süsleyin.', 6),
	(57, 'Önceden ısıtılmış 180 derece fırında 30 dakika pişirin.', 6),
	(58, 'Dilediğiniz gibi servis edebilirsiniz. Afiyet olsun.', 6),
	(59, 'Mercimekleri bol suda yıkayın.Tereyağını eritin ve küp küp doğranmış soğanları ve ezilmiş sarımsakları kavurun.', 7),
	(60, 'Soğan ve sarımsak hafif kavrulunca unu ilave edin ve 2-3 dakika unu kavurun.', 7),
	(61, 'Çırpma teliyle unu çırpıyorken tavuk suyunu ilave edin.', 7),
	(62, 'Mercimekleri de ilave edin ve kalan suyu da ilave edip kaynamaya bırakın.', 7),
	(63, 'Su kaynayınca tuzu ilave edin ve mercimekler iyice yumuşayıncaya kadar pişirin.Kaynayan ve kıvamlanan çorbayı blenderdan geçirin.', 7),
	(64, 'Daha sonra ince delikli bir süzgeçten süzün ve pürüzsüz kıvama getirin.', 7),
	(65, 'Orta boy bir tencerenin içerisine suyu dökün. İçine pirinçleri ekleyin. Kısık ateşte pirinçler yumuşayana kadar pişirin.', 8),
	(66, 'Bir kabın içerisine yoğurt, yumurta ve unu aktarın.', 8),
	(67, 'Güzelce çırpın ve içerisinde unun topaklanmamasına özen gösterin.', 8),
	(68, 'Ocağın üzerinde pişen pirinçlerin suyundan bir kepçe alıp güzelce yoğurtlu karışıma yedirin. Ardından bu işlemi birkaç kepçe daha ilave ederek gerçekleştirin.', 8),
	(69, 'Ocakta pişmekte olan pirinçlerin üzerine yoğurtlu karışımı çok dikkatli bir şekilde, incecik bir ip halinde dökerek bir yandandan da karıştırın.', 8),
	(70, 'Bu şekilde tüm yoğurdu ilave ettikten sonra kaynayana kadar güzelce karıştırın. Kuru naneyi ve tuzunu da ilave edin.', 8),
	(71, 'Birkaç dakika daha ocakta pişirmeye devam edin. Bu aşamada kıvamı çok yoğunlaşırsa su ilave edebilirsiniz.', 8),
	(72, 'Ayrı bir tavanın içerisinde tereyağını eritin ve üzerine kuru naneyi ekleyerek hafifçe yakın. Servis etmeden önce çorbanızın üzerine gezdirin.', 8),
	(73, 'Ardından çorbanızı servis edin. Afiyetler olsun!', 8),
	(74, 'Küçük parçalara ayırdığınız 500 gram brokoliyi 7 su bardağı su ile birlikte haşlayın. Brokoliler haşlandıktan sonra bir kevgir yardımıyla çıkartın ve suyunu bir kenara ayırın.', 9),
	(75, 'Ardından derin bir tencerede 1`er yemek kaşığı zeytinyağı ve tereyağını eritin. 1 yemek kaşığı unu da üzerine ekleyin ve kokusu çıkıp, hafif renk alana kadar kavurun.', 9),
	(76, 'Kavrulan una brokoliyi haşladığınız suyu azar azar ekleyin ve topaklanmaması için bir çırpma teliyle sürekli karıştırın. Bu şekilde 2-3 dakika kaynattıktan sonra haşlayıp süzdürdüğünüz brokolileri suyun içerisine ekleyin.', 9),
	(77, 'Çorbayı, pürüzsüz bir kıvam alması için el blenderından geçirin ve son olarak üzerine 1,5 çay kaşığı tuzla yarım çay kaşığı karabiberi ekleyip karıştırın.', 9),
	(78, 'Brokoli çorbasını bir taşım kaynatıp ocağın altını kapatın ve sıcak olarak servis edin. Afiyet olsun!', 9),
	(79, '1`er adet tavuk göğsünü ve budu, 1 adet iri doğranmış kuru soğan ve 1 tatlı kaşığı tuz ile birlikte tencereye aktarın. Üzerine 6 su bardağı suyu da ekleyin ve orta ateşte 30 dakika kadar kaynatın.', 10),
	(80, 'Pişen tavuk etlerini servis tabağına alın ve soğuduktan sonra kemiklerini ayıklayıp tavuk etlerini didikleyin.', 10),
	(81, 'Çorbayı pişireceğiniz tencerede 1 yemek kaşığı tereyağını eritin. 1 yemek kaşığı unu, kokusu çıkıp, renk alana kadar kavurun.', 10),
	(82, 'Üzerine tavukları haşladığınız ve soğanları ayırdığınız tavuk suyunu yavaş yavaş ve sürekli olarak karıştırarak ekleyip, kapağını kapatıp kaynamaya bırakın.', 10),
	(83, 'Kaynadıktan sonra 1 çay bardağı tel şehriye, haşlayıp didiklediğiniz tavuk eti ve 1 çay kaşığı karabiberi de ekleyin.', 10),
	(84, 'Çorbayı bu şekilde 10 dakika kadar kaynatıp sıcak olarak servis edin.', 10),
	(85, 'Tereyağı, zeytinyağı ve soğanları tencerenin içerisine alın. Hafifçe kavurun.', 11),
	(86, 'Üzerine salçayı ve yıkanmış mercimekleri ilave ederek kavurmaya devam edin.', 11),
	(87, 'Ardından üzerine tüm baharatları, pirinç ve bulguru ekleyerek kavurun. Son olarak suyunu ilave edip kapağını kapatın ve ocağınızın altını kısarak pişmeye bırakın.', 11),
	(88, '15 dakikanın sonunda tencerenizin kapağını açın. Çorbanızı güzelce karıştırın ve servis edin. Afiyetler olsun!', 11),
	(89, 'Sac tavanın içerisine 2 yemek kaşığı sıvı yağı koyun ve kızdırın. Üzerine 1 kilogram kuşbaşı kuzu etini ilave edin.', 12),
	(90, 'Etleri yüksek ateşte suyunu salıp çekene kadar kavurun. Etler hafif kızardığında, iri küpler halinde doğradığınız 2 adet soğanı tavaya ilave edin ve karıştırın.', 12),
	(91, 'Soğanlar sotelendikten sonra 3 adet yeşil köy biberini de tavaya ekleyin. Sac kavurmayı yüksek ateşte pişirdiğimizden dolayı, malzemeler tavanın dibine yapışıp yanmaması için ara ara karıştırın.', 12),
	(92, 'Biberler de sotelendikten sonra 2 adet soyulmuş, küp doğranmış domatesleri ekleyin.', 12),
	(93, 'Domatesler piştikten sonra 1 yemek kaşığı tereyağ ekleyin ve karıştırın.', 12),
	(94, 'Baharatların tümünü ekleyip, 2-3 dakika kaırştırdıktan sonra ocağın altını kapatın ve sıcak olarak servis edin.', 12),
	(95, 'Döküm bir tavada 4 yemek kaşığı zeytinyağını kızdırın. 1 adet yemeklik ince doğradığınız soğanları tavaya ekleyin.', 13),
	(96, 'Renk alan soğanların üzerine 3 adet doğranmış yeşil biber ekleyin ve sotelemeye devam edin.', 13),
	(97, 'Sotelik doğradığınız 600 gram dana etini ilave edin.', 13),
	(98, 'Suyunu salmaması, lezzet ve vitamin değerini hapsetmesi için; yüksek ateşte, yaklaşık 2-3 dakika hiç karıştırmadan mühürleyin.', 13),
	(99, 'Dış kısmı renk alan etleri aralarda karıştırarak yüksek ateşte sotelemeye devam edin.', 13),
	(100, '3 adet soyulmuş ,doğranmış domatesi ekleyerek karıştırın. Ardından 1 çay kaşığı tuz, karabiber, 1 tatlı kaşığı kekiği de ekleyin.', 13),
	(101, 'Birer yemek kaşığı biber ve domates salçasını 1 su bardağı sıcak su ile sulandırdıktan sonra azar azar tavaya ekleyin.', 13),
	(102, 'Kısık ateşte etler yumuşayana kadar pişirin.', 13),
	(103, 'Etleri yumuşayan soteyi, lezzetli suyuyla birlikte servis tabaklarına alın ve sıcak sıcak servis edin. Afiyet olsun!', 13),
	(104, '1 yemek kaşığı sıvı yağ ve 2 yemek kaşığı tereyağını tencerede kızdırın.Üzerine 800 gram dana kuşbaşı etini ekleyin ve etler suyunu salıp çekene kadar kavurun.', 14),
	(105, 'Yemeklik doğranmış 1 adet soğanı ve 3 diş doğranmış sarımsağı da ekledikten sonra etlerle beraber kavurmaya devam edin.', 14),
	(106, 'Bu aşamada ekleyeceğiniz 1 yemek kaşığı unu, kokusu çıkana kadar yaklaşık 2-3 dakika etlerle birlikte kavurun. 1 tatlı kaşığı salçayı ekleyin ve karıştırın.', 14),
	(107, 'Ardından 1 tatlı kaşığı tuz, 1 adet küp doğranmış patates, 1 adet küp doğranmış havuç ve 1 çay kaşığı karabiberi de ekleyip 3 su bardağı su ilave edin.', 14),
	(108, 'Kapağını kapattığınız tencerede, kısık ateşte 30 dakika kadar pişirin.', 14),
	(109, 'Kıvamlı bir sos halini alan suyu ve sebzelerle birlikte pişen eti, sıcak olarak bekletmeden servis edin. Afiyetler olsun!', 14),
	(110, 'Tereyağını derin bir tavanın içine alın. Sarımsağı ilave ederek hafifçe soteleyin', 15),
	(111, 'Ardından minik doğranmış kuşbaşı etleri ekleyerek karıştırın, kapağını kapatıp 6-7 dakika kısık ateşte suyunu salıp pişene kadar bırakın.', 15),
	(112, 'Piştikten sonra salça, toz kırmızı biber ve tuz ekleyerek tatlandırın ve ocaktan alın.', 15),
	(113, 'Közlenmiş patlıcanları kesme tahtasının üzerinde keskin bir bıçak yardımıyla dövün.', 15),
	(114, 'Dövme aşamasında üzerine hafifçe tuz atın.', 15),
	(115, 'İyice ezildiklerinde sarımsaklı yoğurt ile bir kasenin içinde birleştirin ve güzelce karıştırın.', 15),
	(116, 'Servis tabağının içerisine yoğurtlu patlıcanlı karışımı alın. Ortasını çukurlaştırın.Hazırladığınız etleri de üzerine yerleştirin. Sosunu ilave ederek servis edin.', 15),
	(117, 'Eritilmiş tereyağı, sıvı yağ, yumurta ve yoğurdu bir kabın içerisine alıp güzelce çırpın.', 16),
	(118, 'Ardından kabartma tozunu ilave edin. Unu eleyerek azar azar ekleyin.', 16),
	(119, 'Ele yapışmayan yumuşacık bir hamur olana kadar un ilavesiyle güzelce yoğurun.', 16),
	(120, 'Hazırladığınız hamurdan dilediğiniz boyutlarda bezeler koparın. Baş parmağızla hamuru incelterek orta kısmında boşluk oluşturun. İçerisine beyaz peynir ilave edin ve hamurla üzerini örterek yuvarlayın. Bu şekilde tüm hamura şekil verin.', 16),
	(121, 'Poğaçaları yağlı kağıt serili fırın tepsisine dizin.', 16),
	(122, 'Ardından üzerine fırça yardımıyla yumurta sarısı sürün ve çörek otu serpin.', 16),
	(123, '180 derecede önceden ısıtılmış fırında 25-30 dakika, üzeri kızarana kadar pişirin.', 16),
	(124, 'Dinlendirdikten sonra servis edin. Afiyetler olsun!', 16),
	(125, 'Süt, maya ve şekeri karıştırın. Su, sıvı yağ ve yumurta beyazlarını ekleyip çırpın. Tuzu ve kontrollü bir şekilde unu ekleyip karıştırın.', 17),
	(126, 'Hamur kıvam almaya başladığında kabın içinde hafifçe yoğurun ve streç filmle sarıp 45 dakika mayalanmaya bırakın.', 17),
	(127, 'Hamurdan mandalina boyutlarında bezeler kopartın ve elinizde yoğurup silindir şeritler halinde uzatın. İki şeridi birbirine burgu şeklinde sarın ve iki uçtan birleştirip açma şeklini verin.', 17),
	(128, '15 dakika tepside dinlendirin. Ardından yumurta sarısı sürün ve 190 derecede 20 dakika pişirin. Fırından çıkardıktan sonra bir süre dinlendirin. Ardından afiyetle tüketin!', 17),
	(129, 'Bir kasede yarım su bardağı süt, yarım çay bardağı sıvı yağ, yarım su bardağı soda, 2 adet yumurta ve 1 çay kaşığı tuzu ekleyip karıştıralım.', 18),
	(130, '4 adet patatesi haşlayalım ve püre haline gelene dek ezelim.', 18),
	(131, '1 çay kaşığı tuz, yarım çay kaşığı karabiber, 1 çay kaşığı pulbiber, 1,5 su bardağı rendelenmiş kaşar peyniri ve 1 su bardağı yumuşak beyaz peynir ekleyelim ve güzelce karıştıralım.', 18),
	(132, 'Son olarak yarım demet incecik doğradığımız maydanozu da ekleyip karıştırdıktan sonra bol malzemeli iç harcımız hazır!', 18),
	(133, 'Yufkalardan birini tezgaha serelim. İlk başta hazırladığımız sostan yufkanın her yerine gelecek kadar ekleyelim ve sosu yufkanın her yerine yedirelim.', 18),
	(134, 'Hazırladığımız iç harcı yufkanın tam ortasına ekleyip elimizle yufkanın her yerine dağıtalım.', 18),
	(135, 'İç malzemeyi güzelce dağıttıktan sonra yufkanın alt kısmından yukarıya doğru saralım.', 18),
	(136, 'Sardıktan sonra bir ucunu içe doğru kıvırıp rulo haline getirelim. Diğer 2 yufkayı da sarıp tavada pişirme kısmına geçelim.', 18),
	(137, 'Böreği pişireceğimiz tavayı ısıtalım ve 2 tatlı kaşığı tereyağını ekleyip eritelim. Rulo haline getirdiğimiz ilk yufkayı tavanın tam ortasına yerleştirelim ve hazırladığımız diğer yufkaları etrafına saralım.', 18),
	(138, 'Yufkaların tavaya iyice yerleşmesini sağlayalım ve üstte kalan kısma fırça yardımıyla yarım tatlı kaşığı tereyağını sürelim. Böreğimizin her bir yüzünü 5 dakika yüksek ateşte, 15 dakika kısık ateşte pişirelim. Ara ara spatulayla altta kalan yüzeyi kontrol edelim.', 18),
	(139, 'Pişen yüzeyine kalan yarım tatlı kaşığı tereyağını sürelim ve böreği bir servis tabağına alalım. 10 dakika kadar oda sıcaklığında bekletelim ve çıtır çıtır, bol malzemeli tava böreğimizi dilimleip servis edelim.', 18),
	(140, 'Tavukları bir tencerede temiz su ile haşlayın ve piştikten sonra kenara alın. Suyunu süzdürmeyin.', 19),
	(141, 'Büyük boy bir borcamın içerisine cherry domatesleri dikey biçimde yerleştirin.', 19),
	(142, 'Verev kesilmiş havuçları cherry domateslerin yanına gelecek şekilde dizin.', 19),
	(143, 'Bebek patatesleri büyüklüğüne göre ortadan ikiye veya dörde bölüp havuçların yanına dizin.', 19),
	(144, 'Haşlanmış tavukları patateslerin yanına yerleştirin.', 19),
	(145, 'Köy biberlerinin çekirdeklerini çıkartıp uzunlamasına kesin ve tavukların yanına yerleştirin.', 19),
	(146, 'Kırmızı soğanları piyazlık ama çok ince olmayacak şekilde kesin ve köy biberlerinin yanına dizin.', 19),
	(147, 'Başta hazırladığınız sosu borcamdaki sebze ve tavukların üzerine bir kaşık yardımıyla gezdirin.', 19),
	(148, 'Önceden haşlanan tavuğun suyundan 2 kepçe borcama ekleyin.', 19),
	(149, '190 derece fırında 40 dakika pişirin.', 19),
	(150, 'Tabaklara bölüştürüp servis edin.', 19),
	(151, 'Tüm malzemeleri güzelce yıkayın.', 20),
	(152, 'Brokoliyi çiçeklerine ayırın, havucun kabuklarını soyun.', 20),
	(153, 'Patatesin kabuklarını soyun.', 20),
	(154, 'Soğanın kabuklarını soyun ve ince ince doğrayın.', 20),
	(155, 'Sarımsağın kabuğunu soyun ve rendeleyin.', 20),
	(156, 'Tüm sebzeleri tencerenin içine alın, üzerine sıcak su ilave edip pişmeye bırakın.', 20),
	(157, 'Sebzeler yumuşadığında blenderdan geçirin. baharat ve tuzunu ilave edip servis edin.', 20),
	(158, 'Mercimekleri yıkayın ve bir tencereye alıp, üstlerini geçecek kadar su ilave edin. Ocağın altını açın ve yumuşayana dek pişmeye bırakın, yaklaşık 10 dakika.', 21),
	(159, 'Semiz otlarını güzelce yıkayın, irice doğrayın ve bir servis kasesine alın. Pişirdiğiniz mercimekleri süzüp, soğuk suyla yıkadıktan sonra doğradığınız semiz otlarının üstüne alın.', 21),
	(160, 'Sarımsağı rendeleyin, zeytinyağını üstlerine gezdirin.', 21),
	(161, 'Yoğurdu ilave edin ve tuzu da ekledikten sonra güzelce karıştırıp, servis edin.', 21);
/*!40000 ALTER TABLE `directions` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.ingredients
DROP TABLE IF EXISTS `ingredients`;
CREATE TABLE IF NOT EXISTS `ingredients` (
  `ingredient_id` int(11) NOT NULL AUTO_INCREMENT,
  `ingredient` varchar(150) COLLATE utf8_turkish_ci DEFAULT NULL,
  `recipe` int(11) DEFAULT NULL,
  PRIMARY KEY (`ingredient_id`),
  KEY `FK_ingredients_recipes` (`recipe`),
  CONSTRAINT `FK_ingredients_recipes` FOREIGN KEY (`recipe`) REFERENCES `recipes` (`recipe_id`)
) ENGINE=InnoDB AUTO_INCREMENT=224 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.ingredients: ~213 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `ingredients` DISABLE KEYS */;
INSERT INTO `ingredients` (`ingredient_id`, `ingredient`, `recipe`) VALUES
	(11, '2 adet hazır yufka', 1),
	(12, '3 yemek kaşığı sıvı yağ', 1),
	(13, '200 gram orta yağlı kıyma', 1),
	(14, '1 adetorta boy kuru soğan', 1),
	(15, '2 yemek kaşığı sıvı yağ', 1),
	(16, '1,5 yemek kaşığı tereyağı', 1),
	(17, '2 su bardağı ince bulgur', 1),
	(18, '1/2 su bardağı dövülmüş ceviz içi', 1),
	(19, '1/2 demet maydanoz(doğranmış)', 1),
	(20, '1 çay kaşığı tuz', 1),
	(21, '1 çay kaşığıkarabiber', 1),
	(22, '6 adet yufka', 2),
	(23, '1 su bardağı süt', 2),
	(24, '1/2 su bardağı su', 2),
	(25, '1/2 su bardağı sıvı yağ', 2),
	(26, '2 adet yumurta', 2),
	(27, '2 su bardağı kaşar peyniri(rendelenmiş)', 2),
	(28, '2 su bardağı beyaz peynir(ufalanmış)', 2),
	(29, '1/4 demet maydanoz(doğranmış)', 2),
	(30, '1 adet yumurta', 2),
	(31, '2 yemek kaşığı susam', 2),
	(32, '2 adet yufka', 3),
	(33, '1/2 su bardağı tereyağı(eritilmiş)', 3),
	(34, '450 gram lor peyniri', 3),
	(35, '1/2 demet maydanoz', 3),
	(36, '1,5 su bardağı soda', 3),
	(37, '1 adet yumurta sarısı', 3),
	(38, '1 tatlı kaşığı susam', 3),
	(39, '1 tatlı kaşığı çörek otu', 3),
	(40, '3 su bardağı un', 4),
	(41, '1 su bardağı ılık su', 4),
	(42, '1 tatlı kaşığı tuz', 4),
	(43, '2 tatlı kaşığı sirke', 4),
	(44, '300 gram kıyma', 4),
	(45, '1 adet rendelenmiş soğan', 4),
	(46, '1 tatlı kaşığı karabiber', 4),
	(47, '3/4 çay bardağı su', 4),
	(48, '1/2 su bardağısıvı yağ', 4),
	(49, '2 adet yumurta', 5),
	(50, '1 çay bardağı sıvı yağ', 5),
	(51, '1 çay bardağı süt', 5),
	(52, '1/2 paket kabartma tozu', 5),
	(53, '1 çay kaşığı tuz', 5),
	(54, '1/2 çay kaşığı karabiber', 5),
	(55, '1/4 çay kaşığı kimyon', 5),
	(56, '1/2 çay kaşığı pul biber', 5),
	(57, '1/2 çay kaşığı kırmızı toz biber', 5),
	(58, '1 çay bardağı un', 5),
	(59, '1 çay bardağı mısır unu', 5),
	(60, '3 adet patates (kibrit doğranmış)', 5),
	(61, '1 adet soğan (küp doğranmış)', 5),
	(62, '1/2 su bardağı beyaz peynir (ufalanmış)', 5),
	(63, '1/2 demet maydanoz(doğranmış)', 5),
	(64, '1 çay bardağı rendelenmiş kaşar peyniri', 5),
	(65, '1 su bardağı yoğurt', 5),
	(66, '1/4 demet doğranmış maydanoz', 5),
	(67, '5 adet hazır yufka', 6),
	(68, '1 adet yumurta sarısı', 6),
	(69, '2 adet yumurta', 6),
	(70, '1 su bardağı yoğurt', 6),
	(71, '1/2 çay bardağı zeytinyağı', 6),
	(72, '1/2 çay bardağı su', 6),
	(73, '500 gram ıspanak', 6),
	(74, '1 adet soğan', 6),
	(75, '1 çay kaşığı tuz', 6),
	(76, '1 çay kaşığı karabiber', 6),
	(77, '1 tatlı kaşığı çörek otu', 6),
	(78, '1 su bardağı sarı mercimek', 7),
	(79, '1,5 su bardağı tavuk suyu', 7),
	(80, '4 su bardağı su', 7),
	(81, '1 tatlı kaşığı tuz', 7),
	(82, '1 adet soğan', 7),
	(83, '2 diş sarımsak', 7),
	(84, '1 yemek kaşığı tereyağı', 7),
	(85, '1 yemek kaşığı un', 7),
	(86, 'Üzeri İçin: 2 yemek kaşığı tereyağı', 7),
	(87, '1 çay kaşığıpul biber', 7),
	(88, '2 litre su', 8),
	(89, '5-6 yemek kaşığı pirinç', 8),
	(90, '1 yemek kaşığı (tepeleme)un', 8),
	(91, '1 adet yumurta', 8),
	(92, '1,5 su bardağı yoğurt', 8),
	(93, '2 çay kaşığı tuz', 8),
	(94, '1 tatlı kaşığı kuru nane', 8),
	(95, '2 yemek kaşığı tereyağı', 8),
	(96, '2 çay kaşığı kuru nane', 8),
	(97, '500 gram brokoli', 9),
	(98, '7 su bardağı su', 9),
	(99, '1 yemek kaşığı zeytinyağı', 9),
	(100, '1 yemek kaşığı tereyağı', 9),
	(101, '1 yemek kaşığı un', 9),
	(102, '1,5 çay kaşığı tuz', 9),
	(103, '1/2 çay kaşığı karabiber', 9),
	(104, '1 adet tavuk göğsü', 10),
	(105, '1 adet tavuk budu', 10),
	(106, '1 adet kuru soğan', 10),
	(107, '1 tatlı kaşığı tuz', 10),
	(108, '6 su bardağı su', 10),
	(109, '1 yemek kaşığı tereyağı', 10),
	(110, '1 yemek kaşığı un', 10),
	(111, '1 çay bardağı tel şehriye', 10),
	(112, '1/2 çay kaşığı karabiber', 10),
	(113, '1 su bardağı kırmızı mercimek', 11),
	(114, '1 adet büyük boy soğan', 11),
	(115, '2 yemek kaşığı biber salçası', 11),
	(116, '1 yemek kaşığı tereyağı', 11),
	(117, '1/2 çay bardağı sıvı yağ', 11),
	(118, '1 yemek kaşığı pirinç', 11),
	(119, '2 yemek kaşığı bulgur', 11),
	(120, '1 tatlı kaşığı pul biber', 11),
	(121, '1 çay kaşığı karabiber', 11),
	(122, '6 - 6,5 su bardağı sıcak su', 11),
	(123, '1 çay kaşığı tuz', 11),
	(124, '2 yemek kaşığı sıvı yağ', 12),
	(125, '1 kg.kuşbaşı et (kuzu ya da orta yağlı dana eti)', 12),
	(126, '2 adet soğan(iri küpler halinde doğranmış)', 12),
	(127, '3 adet köy biberi(doğranmış)', 12),
	(128, '2 adet domates(soyulmuş, küp doğranmış)', 12),
	(129, '1 yemek kaşığı tereyağı', 12),
	(130, '1 tatlı kaşığı tuz', 12),
	(131, '1 çay kaşığı karabiber', 12),
	(132, '1 çay kaşığı pul biber', 12),
	(133, '1 çay kaşığı kekik', 12),
	(134, '600 gram sotelik dana eti', 13),
	(135, '4 yemek kaşığı zeytinyağı', 13),
	(136, '1 adet orta boy kuru soğan(yemeklik doğranmış)', 13),
	(137, '2 adet orta boy domates(kabukları soyulmuş, doğranmış)', 13),
	(138, '3 adet orta boy yeşil biber(doğranmış)', 13),
	(139, '1 tatlı kaşığı domates salçası', 13),
	(140, '1/2 tatlı kaşığı biber salçası', 13),
	(141, '1 su bardağı sıcak su', 13),
	(142, '1 çay kaşığı tuz', 13),
	(143, '1/2 çay kaşığı taze çekilmiş tane karabiber', 13),
	(144, '1 tatlı kaşığı kekik', 13),
	(145, '800 gram kuşbaşı dana eti', 14),
	(146, '1 yemek kaşığı ayçiçek yağı', 14),
	(147, '2 yemek kaşığı tereyağı', 14),
	(148, '1 adet orta boy kuru soğan', 14),
	(149, '3 diş sarımsak', 14),
	(150, '1 yemek kaşığı un', 14),
	(151, '1 tatlı kaşığı domates salçası', 14),
	(152, '1 tatlı kaşığıtuz', 14),
	(153, '2 adet orta boy patates', 14),
	(154, '1 adet orta boy havuç', 14),
	(155, '3 su bardağı sıcak su', 14),
	(156, '4 adet tane karabiber', 14),
	(157, '1 diş sarımsak', 15),
	(158, '250 gram kuşbaşı et (küçük doğranmış)', 15),
	(159, '50 gram tereyağı', 15),
	(160, '1 yemek kaşığı biber salçası', 15),
	(161, '1 çay kaşığı toz kırmızı biber', 15),
	(162, '1 çay kaşığı tuz', 15),
	(163, '3 adet közlenmiş patlıcan', 15),
	(164, '1 kase sarımsaklı yoğurt', 15),
	(165, '1 su bardağı eritilmiş tereyağı', 16),
	(166, '1 adet yumurta', 16),
	(167, '1 çay bardağı sıvı yağ', 16),
	(168, '1 su bardağı yoğurt', 16),
	(169, '2 paket kabartma tozu', 16),
	(170, '1,5 çay kaşığı tuz', 16),
	(171, '2,5 - 3 su bardağı un', 16),
	(172, '200 gram beyaz peynir', 16),
	(173, '1 adet yumurta sarısı', 16),
	(174, '2-3 yemek kaşığı çörek otu', 16),
	(175, '1 su bardağı ılık süt', 17),
	(176, '1 paket instant maya(10 g)', 17),
	(177, '3 yemek kaşığı toz şeker', 17),
	(178, '1 su bardağı ılık su', 17),
	(179, '1 su bardağı sıvı yağ', 17),
	(180, '2 adet yumurta beyazı', 17),
	(181, '1 tatlı kaşığı tuz', 17),
	(182, '7 su bardağı un', 17),
	(183, '2 adet yumurta sarısı', 17),
	(184, '4 adet haşlanmış patates', 18),
	(185, '1 çay kaşığı tuz', 18),
	(186, '1/2 çay kaşığı karabiber', 18),
	(187, '1 çay kaşığı pul biber', 18),
	(188, '1,5 su bardağı rendelenmiş kaşar peyniri', 18),
	(189, '1 subardağı beyaz peynir(yumuşak, ufalanmış)', 18),
	(190, '1/2 demet kıyılmış maydanoz', 18),
	(191, '3 adet yufka', 18),
	(192, '1/2 su bardağı kaşar peyniri', 18),
	(193, '3 tatlı kaşığı tereyağı', 18),
	(194, '300 gram cherry domates', 19),
	(195, '2 adet havuç', 19),
	(196, '300 gram bebek patates', 19),
	(197, '3 adet haşlanmış tavuk göğsü', 19),
	(198, '6 adet köy biberi', 19),
	(199, '2 adet kırmızı soğan', 19),
	(200, '2 kepçe tavuksuyu', 19),
	(201, '5 dal taze kekik', 19),
	(202, '1 su bardağı zeytinyağı', 19),
	(203, '1 adet misket limonu rendesi', 19),
	(204, '1 çay kaşığı tuz', 19),
	(205, '1 çay kaşığı karabiber', 19),
	(206, '1 tatlı kaşığı tozkırmızı biber', 19),
	(207, '3 diş sarımsak', 19),
	(208, '1 demet ıspanak', 20),
	(209, '1/4 adet patates', 20),
	(210, '1/3 adet kabak', 20),
	(211, '1/2 adet brokoli', 20),
	(212, '1 adet orta boy havuç', 20),
	(213, '1 adet kırmızı soğan', 20),
	(214, '1 diş sarımsak', 20),
	(215, '1 çay kaşığı kimyon', 20),
	(216, '1 çay kaşığı deniz tuzu', 20),
	(217, '1 çay kaşığı karabiber', 20),
	(218, '1 bağ semizotu', 21),
	(219, '1 çay bardağı yeşil mercimek', 21),
	(220, '1 su bardağı yoğurt', 21),
	(221, '3 yemek kaşığı zeytinyağı', 21),
	(222, '2 diş sarımsak', 21),
	(223, '1 silme tatlı kaşığı tuz', 21);
/*!40000 ALTER TABLE `ingredients` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.recipes
DROP TABLE IF EXISTS `recipes`;
CREATE TABLE IF NOT EXISTS `recipes` (
  `recipe_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8_turkish_ci DEFAULT NULL,
  `image` varchar(150) COLLATE utf8_turkish_ci DEFAULT NULL,
  `description` varchar(500) COLLATE utf8_turkish_ci DEFAULT NULL,
  `prep_time` int(11) DEFAULT NULL,
  `calories` int(11) DEFAULT NULL,
  `serves` int(11) DEFAULT NULL,
  `create_date` date DEFAULT NULL,
  `visible` tinyint(4) DEFAULT NULL,
  `read_score` int(11) DEFAULT 0,
  `category` int(11) DEFAULT NULL,
  PRIMARY KEY (`recipe_id`),
  KEY `FK_recipes_categories` (`category`),
  CONSTRAINT `FK_recipes_categories` FOREIGN KEY (`category`) REFERENCES `categories` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.recipes: ~21 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `recipes` DISABLE KEYS */;
INSERT INTO `recipes` (`recipe_id`, `title`, `image`, `description`, `prep_time`, `calories`, `serves`, `create_date`, `visible`, `read_score`, `category`) VALUES
	(1, 'Avcı Böreği', 'avci-boregi.jpg', 'Kuru soğanla tereyağında kavrulmuş kıyma, sıcak suyu çekip şişen ince bulgur, ceviz içi ve baharatlar... Tüm bu lezzetli malzemelerle hazırlanmış iç harç, hazır yufka parçalarına sarmalanıyor. Üzerleri çırpılmış yumurta ve galeta unuyla kaplandıktan sonra damak tadınıza göre fırında ya da derin yağda kızartılıyor.', 20, 250, 8, '2021-01-19', 1, 5, 1),
	(2, 'Kolay Su Böreği', 'kolay-su-boregi.jpg', 'Geleneksel tarifleri aslına uygun şekilde pratikleştirmek pek kolay değil elbet, geleneksel mutfağımız adeta sabrın bir örneği. Ancak çalışan kesimin yoğunlaşması ile geleneksel tarifleri pratikleştirmek şart oluyor. Hal böyle olunca su böreği de pratikleştirmek için can attığımız tariflerden, hem çok sevilen hem de vazgeçemediklerimizden su böreği bu tarifte açma yufkalarının yerini hazır yufkalara bırakıyor derin bir hüzünle, ama olsun ona saygımız sonsuz, hatta vaktimiz olduğunda orijinalini ', 50, 350, 10, '2021-01-19', 1, 35, 1),
	(3, 'Soda Banyolu Börek', 'soda-banyolu-borek.jpg', 'Börek tarifleri denilince akla su böreği, sigara böreği, kol böreği gibi klasik lezzetler gelir.  Kahvaltıda tüketilmesi ayrı, çayın yanında sıcacık yenmesi ayrı bir keyif olan böreklere kimse hayır diyemez. Mutlaka herkesin favorisi bir börek vardır   Hele bir de bol bol peynirli, içi tam kıvamında pişmiş bir börek söz konusuysa yüzlerde kocaman bir mutluluk gülümsemesi oluşur! Peki hem lezzetli hem de pratik bir börek tarifimiz var desek ? O zaman sizi nefis bir tarifle buluşturalım! Puf gibi ', 50, 270, 12, '2021-01-19', 1, 71, 1),
	(4, 'Çiğ Börek', 'cig-borek.jpg', 'Tatarlar`ın bize en güzel armağanlarından biri çi börek. Çiğ börek adıyla da bilinen bu lezzet özellikle Eskişehir`in her köşesinde yapılan ve çok sevilerek yenen bir güzellik üstelik. Böreğin özelliği olarak kıymalı harcı çiğden konuluyor. İncecik açılmış hamurun içerisine konup kızgın yağda hızlı bir şekilde pişiyor.', 35, 175, 6, '2021-01-19', 1, 45, 1),
	(5, 'Emekli Böreği', 'emekli-boregi.jpg', 'Bu börekte yufka yok, hamur açmak yok! Bir kasede tüm malzemeyi karıştırıp, çay saatine börek tadında enfes bir tarif hazırlamaya ne dersiniz? Yufkasız ve el açması hamursuz bir börek tarifi arıyorsanız, bu tarife bayılacaksınız! Börek tadında ve oldukça pratik bir tarif hazırladık. Emekli böreği, börek yapmaya üşenenler ve zamanı kısıtlı olanların favorisi olacak. Sofraların en sevilen tariflerinden biri olacak emekli böreğini evde bulunan malzemelerle kolaylıkla hazırlayabilirsiniz. Ayrıca, iç', 55, 345, 6, '2021-01-19', 1, 12, 1),
	(6, 'Ispanaklı Börek', 'ispanakli-borek.jpg', 'Ispanağın yararını saymakla bitiremeyiz. Sevenin çok sevdiği ıspanak, bazı kimselerce de mesafeli davranılan sebzelerden biri. Sevmeyenin bile afiyetle yiyebileceği bir tarifle tüm bu ön yargıları kıralım öyleyse. Şöyle sıcacık, kıtır kıtır bir böreği kim sevmez ki? Hazırlaması oldukça pratik, saatlerce hamur açmanıza gerek kalmadan hazır yufka ile çabucak halledeceğiniz bir börek için mutfağa buyurun!', 50, 310, 5, '2021-01-19', 1, 87, 1),
	(7, 'Mercimek Çorbası', 'mercimek-corbasi.jpg', 'Bu nefis lezzeti ev konforunda yaşayın istedik. Bu sefer soğuk kış günleri evde kendinizi lokanta usulü çorbayla şımartın bizce. Eh önümüzde çetin bir kış bizi bekliyor. Sarı mercimeğin güzeller güzeli rengine... Hem blenderdan çekilip hem de süzgeçten süzülen pürüzsüz dokusuna saygı duruşunda bulunuyor ve tarifi sizinle buluşturuyoruz.', 40, 150, 4, '2021-01-19', 1, 112, 1),
	(8, 'Pirinçli Yoğurt Çorbası', 'pirincli-yogurt-corbasi.jpg', 'Mevsim farketmeden afiyetle içilecek bir çorba varsa o da tartışmasız pirinçli yoğurt çorbasıdır. Yemek tarifleri arasında özel bir yeri olan bu çorba o her daim tüketilecek kadar güzel lezzetini yoğurda borçlu. Üstelik hazırlaması da öyle pratik ki! Terbiyesi kesilmeyen, tadı damağınızda kalacak bu nefis lezzeti hazırlamak isteyenler için adım adım resimli anlatımla tarifimizi sizler için hazırladık.', 40, 175, 4, '2021-01-19', 1, 54, 2),
	(9, 'Brokoli Çorbası', 'brokoli-corbasi.jpg', 'Çorba tariflerinin içinde özel bir yeri olan bu brokoli çorbası üstelik herkese göre! Çünkü hem kremasız hem sütsüz bir brokoli çorbası tarifi bu. Bu sade brokoli çorbası diyet listelerinin de gözdesi. Daha ne olsun? Hazırladığınız çorbayı şifa niyetine bu şekilde içebileceğiniz gibi krema ile tatlandırarak da tüketebilirsiniz tabii, öyle de oldukça lezzetli oluyor.', 30, 150, 4, '2021-01-19', 1, 567, 2),
	(10, 'Tavuk Suyu Çorbası', 'tavuk-suyu-corbasi.jpg', 'Mercimek çorbası ve ezogelin çorbasıyla birlikte restoran lezzetlerinin vazgeçilmezleri arasında yer alan tavuk suyu çorbası diğer çorbalara bakıldığında görece bir kaşık daha lezzetlidir.', 100, 378, 6, '2021-01-19', 1, 678, 2),
	(11, 'Ezogelin Çorbası', 'ezogelin-corbasi.jpg', '', 25, 123, 6, '2021-01-19', 1, 89, 2),
	(12, 'Sac Kavurma', 'sac-kavurma.jpg', 'Sac üzerinde yapılan nefis kavurma, biber, soğan ve domatesle lezzetlenip sadece temel birkaç baharatla lezzetini zirveye taşıyor. Eğer sac tavanız yoksa üzülmeyin, vok tava veya ince tabanlı bir tavada da sac keyfi yaşayabilir ve misafirlerinize yaptığınız bu yemeği ziyafete dönüştürebilirsiniz. Bayram sofralarını, özel günleri, şık sofraları şölene çeviren nefis, yumuşacık pişmiş sac kavurma yapmaya ne dersiniz?', 45, 452, 6, '2021-01-19', 1, 9, 3),
	(13, 'Et Sote', 'et-sote.jpg', 'Etli yemeklerin en kolay ve en dikkatli şekilde pişirilmesi de şart olan tariflerinin başında geliyor kendileri. Yüksek ısıda mühürlemek, soğan ve domatesini mutlaka ilave etmek şart. Yanına bir pilav ve salatayla en şahane öğüne dönüşüyor. Adım adım resimli anlatımıyla et sote tarifimizi denemeye davetlisiniz.', 70, 358, 4, '2021-01-19', 1, 56, 3),
	(14, 'Tas Kebabı', 'tas-kebabi.jpg', 'Kuşbaşı dana etiyle yapılan en güzel yemeklerden olan, sulu et yemeklerinin en sevileni tas kebabında etleri yumuşacık, lokum gibi pişiriyoruz. Tüm püf noktalarını da sesli olarak videomuzda adım adım anlatıyoruz.', 70, 320, 5, '2021-01-19', 1, 89, 3),
	(15, 'Alinazik', 'alinazik.jpg', 'Adı da, hikayesi de kendi kadar güzel olan bu yemeği en güzel Antep`te, onların elinden yemek gerek. Ama gitme şansı olmayanlar için bir yol daha var. Üstelik pek pratik. Bu müthiş görsel şölen için sıvayın hadi kollarınızı. Biz bu tarifte kuşbaşı etleri minik minik doğradık. Anca dilerseniz satır eti, kıyma ya da kuşbaşı kullanarak tarifi hazırlamanız mümkün.', 30, 310, 4, '2021-01-19', 1, 23, 3),
	(16, 'Şipşak Poğaça', 'sipsak-pogaca.jpg', 'Poğaçanın özelliği içerisinde yoğurt ve kabartma tozu olmasında saklı. Maya olmasa bile bu iki malzeme sayesinde hem kabarıyorlar hem de kıvamları şahane oluyor. İçine farklı malzemeler ilave ederek ya da hiçbir şey ilave etmeden de yapabilirsiniz. Şimdiden ellerinize sağlık diyoruz.', 35, 280, 12, '2021-01-19', 1, 34, 4),
	(17, 'Yağlı Açma', 'yagli-acma.jpg', 'İster zengin kahvaltı sofralarında ekmek yerine, ister hafta arası koşuşturmalarında kahvaltı niyetine, ister  çocukların beslenme çantalarında, isterseniz de çay saatlerinde tüketilebilecek bu açma tarifi, bayatlamamasıyla kurtarıcınız olacak. Yumuşacık kabaran mayalı hamurunun lezzetine varmak için haydi zaman kaybetmeden sizi mutfağa alalım!', 45, 290, 6, '2021-01-19', 1, 566, 4),
	(18, 'Tava Böreği', 'tava-boregi.jpg', 'Öğrenciye, tembele, yemek yapmayı bilmeyene, ani gelen misafire, sabah kahvaltıya, naz yapan kocaya, hamur işi krizine iyi gelir.  Bilin bakalım bu nedir? Börek, çay sofralarının olmazsa olmazı, kahvaltının en leziz alternatifidir. Yanında bir kısır, bir de çay verdiniz mi fethedemeyeceğiniz gönül kalmaz.', 60, 315, 8, '2021-01-19', 1, 98, 4),
	(19, 'Fırında Gökkuşağı', 'firinda-gokkusagi.jpg', 'Yeşil renkli sebzeler, toksinlerin atılımını sağlamakla birlikte, bazı kanser risklerinin azaltılmasında, göz sağlığında, kas ve kemiklerin yenilenmesinde ve sağlıklı dişlere sahip olmada büyük yarar sağlıyorlar. Kırmızı sebzeler, hafızayı güçlendirici ve iltihap giderici özelliğe sahip. Sarı renkli sebzeler, beyin fonksiyonlarını düzenlemede ve cilt güzelliğinde rol oynuyor. Turuncu sebzeler, antioksidan yönünden çok zengin ve bağışıklık sistemini güçlendiriciler. Mor renkli sebzeler ise adeta ', 55, 130, 3, '2021-01-19', 1, 55, 5),
	(20, 'Yeşil Detoks Çorbası', 'yesil-detoks-corbasi.jpg', 'Yaz meyveleri, hafif yemekler, hareketli günler... Hava sıcaklığı düşüp, manav tezgahlarındaki karpuzlara, çileklere veda edince, az hareketli kış günleri başlıyor. Yazın o enerjisi yerine, evde daha çok vakit geçiren, enerjisi daha düşük insanlara dönüşüyoruz.Haliyle yemek yeme ihtiyacımız artıyor, formumuzu biraz yitiriyoruz. Şişkinlikler, ödemlerde beraberinde geliyor. Bu biraz karamsar tabloyu renklendirmek, size kendinizi daha hafif hissettirmek adına bir önerimiz var. Sebzelerle hazırlanan', 25, 100, 4, '2021-01-19', 1, 345, 5),
	(21, 'Mercimekli Semizotu Salatası', 'mercimekli-semizotu-salatasi.jpg', 'Yemeği de yapılan semizotunun en faydalı tüketim şekli tabi ki onu çiğ olarak tüketmek ve bunun için sizlere harika bir tarif önerimiz var. Yeşil mercimekle semizotunun birleşimine hayran olacak, sarımsak ve yoğurtla zirveye taşınan bu lezzete kendinizi kaptıracaksınız. Haydi bakalım, mutfağa. Afiyetler olsun.', 20, 90, 4, '2021-01-19', 1, 3456, 5);
/*!40000 ALTER TABLE `recipes` ENABLE KEYS */;

-- tablo yapısı dökülüyor recipes.users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(80) COLLATE utf8_turkish_ci DEFAULT NULL,
  `password` varchar(100) COLLATE utf8_turkish_ci DEFAULT NULL,
  `type` char(5) COLLATE utf8_turkish_ci DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- recipes.users: ~2 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`user_id`, `email`, `password`, `type`) VALUES
	(1, 'ali@gel.com', '12345', 'admin'),
	(2, 'veli@git.com', '12345', 'user');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
